### ISSUE TITLE
Investigation of low-coverage amplicon regions

### ISSUE THREAD

**Issue by hoelzer** [Psy-Fer/CoVarPlot#7]
As a suggestion: from looking at a couple of plots now I wonder if it makes sense to have a logarithmic (?) y-axis? This would make inspections at around 20X coverage easier? 

This could be also an additional parameter to switch from "linear" y-axis to logarithmic?

**Comment by Psy-Fer** [comment]
Yep, you are the 3rd to suggest this
I'll make it so. 
(grant stuff and my 2bd Pfizer shot held me up, but this week for all the changes)

**Comment by Psy-Fer** [comment]
Log scale now available with `-l, --log` with commit https://github.com/Psy-Fer/CoVarPlot/commit/280638ce129fe3fbd0902e6caab150e6fa17a1b8 

Also a note about `--show`, if you pres l (L) while the windo is open, it will change the scale to log
